# Stubs for glob
# Based on http://docs.python.org/3/library/glob.html

import sys
from typing import AnyStr, Iterator, List

if sys.version_info >= (3, 5):
    def glob(pathname: AnyStr, *, recursive: bool = ...) -> List[AnyStr]: ...
    def iglob(pathname: AnyStr, *, recursive: bool = ...) -> Iterator[AnyStr]: ...

else:
    def glob(pathname: AnyStr) -> List[AnyStr]: ...
    def iglob(pathname: AnyStr) -> Iterator[AnyStr]: ...

if sys.version_info >= (3, 4):
    def escape(pathname: AnyStr) -> AnyStr: ...
